<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Forever\Blog\Block\TagList;

$tags = $block->getTagList();
if ($tags && $tags->getSize()): ?>
    <div class="mp-sidebar mpcss">
        <div class="row">
            <div class="block-title col-xs-12 sidebar-tags">
                <p class="block-mp-sidebar-heading" role="heading" aria-level="2">
                    <?= $block->escapeHtml(__('Tags')) ?>
                </p>
            </div>
            <div class="col-xs-12">
                <?php foreach ($tags as $tag): ?>
                    <a class="label label-default tags-list"
                       style="font-size:<?= $block->escapeHtmlAttr($block->getTagSize($tag)) . 'px'; ?>"
                       href="<?= /* @noEscape */ $block->getTagViewUrl($tag->getTitle())?>">
                        <?= $block->escapeHtml($tag->getTitle()) ?>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
