<?php

use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$productCollection = $block->getLoadedProductCollection();
$isEnabled = $block->isModuleEnabled();
?>
<div class="home-page-product-slider bestseller-slider-section reveal">
    <?php if ($isEnabled):?> 
        <?php if (!$productCollection->count()):?>
                <div class="page-title-wrapper">
                    <h3 class="page-title">
                        <span><?=/* @noEscape */ __("Best Seller Products")?></span>
                    </h3>
                </div>
                <div class="message info empty"><div>
                    <?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
                </div>
    <?php else:?>
        <div class="page-title-wrapper">
            <h3 class="page-title">
                <span><?= /* @noEscape */__("Best Seller Products") ?></span>
            </h3>
        </div>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
            <ol class="products list items product-items">
                <div class="owl-carousel owl-theme bestseller-slider product-slider">
                <?php /** @var $product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($productCollection as $product):?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <div class="product-image-section">
                        
                            <?php
                            $productImage = $block->getImage($product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <?php
                                $isEnable = $block->getImageSwitcherConfigValue();
                            ?>
                            <?php if ($isEnable): ?>
                                <div class="flip-box">
                                    <?php
                        // display the product label
                        if ($select = $product->getProductoption()): 
                            $selectAttr =  $product->getResource()->getAttribute('productoption');
                                if ($selectAttr->usesSource())
                                    {
                                        $select = $selectAttr->getSource()->getOptionText($select);
                                        $productoption = strtolower(str_replace(' ', '_', $select));
                                    }
                             endif;
                    $productlabel = $block->getProductlabel($product);
                    $confproductlabel = $block->getScopeconfig('productlabel/general/productlabelenable');
                    if ($confproductlabel && !empty($productlabel[0])):?>
                        <div class="product_label_wrapper <?= /* @noEscape */ $productoption ?>"><?php
                            foreach ($productlabel as $productlabelvalue):
                                if ($productlabelvalue):?>
                                    <span class="productlabel <?= /* @noEscape */
                                    is_numeric($productlabelvalue) ?
                                    'discount' :strtolower(str_replace(' ', '', $productlabelvalue)) ?>">
                                        <?php if (is_numeric($productlabelvalue)):
                                            $sign = '% off';?>
                                            <?= /* @noEscape */ $productlabelvalue.$sign ?>
                                        <?php else: ?>    
                                            <?= /* @noEscape */ $productlabelvalue ?>
                                        <?php endif; ?>        
                                    </span><?php
                                endif;
                            endforeach;?>
                        </div>
                    <?php endif; 
                        // display the product label?>
                                    <div class="flip-box-inner">
                                        <div class="flip-box-front">
                                            <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
                                               class="product photo product-item-photo"
                                               tabindex="-1">
                                                <?= $productImage->toHtml() ?>
                                            </a>
                                        </div>
                                        <?php $productImageUrl = $block->getImageUrl($product); ?>
                                        <div class="flip-box-back">
                                            <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
                                               class="product photo product-item-photo"
                                               tabindex="-1">
                                                <img src="<?= /* @noEscape */ $productImageUrl ?>"
                                                    alt="<?= /* @noEscape */ $product->getName() ?>"
                                                    style="width:100%;height:100%">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php else: ?>
                                <a class="product photo product-item-photo"
                                    href="<?= /* @noEscape */ $product->getProductUrl(); ?>"
                                >
                                    <?= /* @noEscape */$productImage->toHtml()  ?></a>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"
                                <?= strpos($pos, $viewMode . '-actions') ?
                                $block->escapeHtmlAttr($position) : '' ?>>

                                <a class="quickview forever-quickview forever-quickview-text"
                                    data-quickview-url="http://magentotheme.ictstagingsite.com/quickview/catalog_product/view/id/<?= $product->getId() ?>/"
                                    data-forever-js="quickview-item-default"
                                     href="http://magentotheme.ictstagingsite.com/quickview/catalog_product/view/id/<?= $product->getId() ?>/">
                                    <span>Quickview</span>
                                </a>

                                <div class="actions-primary"
                                <?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                        <form data-role="tocart-form"
                                                data-product-sku="<?= $block->escapeHtmlAttr($product->getSku()) ?>"
                                                action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                method="post">
                                            <input type="hidden"
                                                    name="product"
                                                    value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="
                                            <?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                    value="<?= /* @noEscape */ $postParams['data']
                                                    [Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else:?>
                                        <?php if ($product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                            </div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                      <?php
                                                $values = $block->getAuthenticationpopup();
                                                if($values == 1){ ?>
                                                    <a href="#"
                                                    onclick="addProductToWishlist(this)"
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   product-id='<?= /* @noEscape */ $productId = json_decode($block->getAddToWishlistParams($product), true)['data']['product'] ?>'
                                                   title="<?= /* @noEscape */ __('Add to Wish List') ?>">
                                                    <span><?= /* @noEscape */__('Add to Wish List') ?></span>
                                                </a>

                                                    <script>
                                                    window.addProductToWishlist = function (obj) {
                                                        if(!parseInt(obj)){
                                                            var id = obj.getAttribute('product-id');
                                                        }else{
                                                            var id = obj;
                                                        }
                                                        
                                                        require(["jquery"], function($){
                                                            $.ajax({
                                                                url: '<?php echo $this->getUrl('ajaxlogin/index/addtowishlist') ?>',
                                                                method: 'get',
                                                                data: { productId: id},
                                                                dataType: 'json',
                                                                showLoader:true,
                                                                success: function(data){
                                                                    if(data.status=="400"){
                                                                        localStorage.removeItem('wishlist_elem');    
                                                                        localStorage.setItem('wishlist_elem', id);
                                                                        $('.trigger-ajax-login').eq(0).trigger('click');
                                                                    }else{
                                                                        var redirect = data.redirect;
                                                                        localStorage.removeItem('wishlist_elem');
                                                                        if(redirect) {
                                                                            window.location.href = '<?php echo $this->getUrl('wishlist/index/index') ?>';
                                                                        } else {
                                                                          <?php echo "success"; ?> 
                                                                        }
                                                                    }
                                                                }
                                                            });


                                                        });
                                                    }
                                                    </script>
                                                    <?php }else{ ?>

                                                        <a href="#"
                                                       data-post='<?= /* @noEscape */
                                                        $block->getAddToWishlistParams($product); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?= /* @noEscape */ __('Add to Wish List') ?>">
                                                        <span><?= /* @noEscape */__('Add to Wish List') ?></span>
                                                    </a>

                                                 <?php } ?>
                                    
                                    <a href="#" 
                                        data-post='<?= /* @noEscape */
                                        $block->getCompareHelper()
                                        ->getPostDataParams($product);?>'
                                        class="action tocompare"
                                        data-action="add-to-compare"
                                        title="<?= /* @noEscape */__('Add to Compare') ?>">
                                        <span><?= /* @noEscape */ __('Add to Compare') ?></span>
                                    </a>
                                </div>
                                </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $block->productAttribute(
                                            $product,
                                            $product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"
                                           title="<?= /* @noEscape */ $productNameStripped ?>"
                                           class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                                   
                            </div>
                        </div>
                        <div class="product details product-item-details">
                            <?php
                                $productNameStripped = $block->stripTags($product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="
                                   <?= $block->escapeUrl($product->getProductUrl()) ?>">
                                    <?= /* @noEscape */ $block->productAttribute(
                                        $product,
                                        $product->getName(),
                                        'name'
                                    ) ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($product, $templateType) ?>
                            <?= /* @noEscape */ $block->getProductPrice($product) ?>
                            <?php if ($product->isAvailable()):?>
                                <?= $block->getProductDetailsHtml($product) ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </div>
            </ol>
        </div>
        
        <?php if (!$block->isRedirectToCartEnabled()):?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($product->getSku()) ?>"
                    }
                }
            }
            </script>
        <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?> 
</div>
<script>
require(['jquery','jquery/ui','owlCarousel'], function ($) {
    $(document).ready(function(){
        $(function() {
            $(".bestseller-slider").owlCarousel({
                responsive:{
                    0:{
                        items:1
                    },
                    480:{
                        items:2
                    },
                    768:{
                        items:2
                    },
                    992:{
                        items:2
                    },
                    1024:{
                        items:3
                    },
                    1200:{
                        items:3
                    }
                },
                autoplay:false,
                loop:false,
                nav : true, // Show next and prev buttons
                dots: false,
                autoplaySpeed : 500,
                navSpeed : 500,
                dotsSpeed : 500,
                autoplayHoverPause: true,
                items:4,
            });
        })
    });
});
</script>
