<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php
    $viewModel = $block->getViewmodels();
    $enable = $viewModel->getScopeconfig();
if ($enable == 1) {
    if ($block->isWishListAllowed()): ?>
    <a href="#"
       onclick="addProductToWishlist(this)"
       class="action towishlist"
       product-id='<?= /* @noEscape */$productId = json_decode($this->getWishlistParams(), true)['data']['product'] ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>

<script>
window.addProductToWishlist = function (obj) {
    if(!parseInt(obj)){
        var id = obj.getAttribute('product-id');
    }else{
        var id = obj;
    }
    
    require(["jquery"], function($){
        $.ajax({
            url: '<?= /* @noEscape */ $this->getUrl('ajaxlogin/index/addtowishlist') ?>',
            method: 'get',
            data: { productId: id},
            dataType: 'json',
            showLoader:true,
            success: function(data){
                if(data.status=="400"){
                    localStorage.removeItem('wishlist_elem');    
                    localStorage.setItem('wishlist_elem', id);
                    $('.trigger-ajax-login').eq(0).trigger('click');
                }else{
                    var redirect = data.redirect;
                    localStorage.removeItem('wishlist_elem');
                    if(redirect) {
                        window.location.href = '<?= /* @noEscape */ $this->getUrl('wishlist/index/index') ?>';
                    } else {
                      <?= /* @noEscape */ "success"; ?> 
                    }
                }
            }
        });


    });
}
</script>

   <?php } else {
    if ($block->isWishListAllowed()): ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
 <?php  } ?>
    
