<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php $widget = $this->helper(
        \Magento\Framework\Json\Helper\Data::class
    )->jsonDecode(
        $block->getWidgetOptionsJson()
    );
        $widgetOptions = $this->helper(
            \Magento\Framework\Json\Helper\Data::class
        )->jsonEncode(
            $widget['productListToolbarForm']
        );
    ?>
    <div class="toolbar toolbar-products"
    data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= /* @noEscape */ $block->fetchView(
                $block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')
            ) ?>
        <?php else: ?>
            <?php if ($block->isExpanded()): ?>
                <?= /* @noEscape */ $block->fetchView(
                    $block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')
                ) ?>
            <?php endif ?>
            <?= /* @noEscape */ $block->fetchView(
                $block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')
            ) ?>
            <?php if ($block->isExpanded()): ?>
                <?= /* @noEscape */ $block->fetchView(
                    $block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')
                ) ?>
            <?php endif ?>
        <?php endif ?>
        <?php echo $this->getLayout()->createBlock(
            \Forever\Core\Block\ZoomInOut::class
        )->setTemplate(
            "Forever_Core::zoom_in_out.phtml"
        )->toHtml() ?>
    </div>
<?php endif ?>
