<?php

/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_RMA
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

/** @var \Ict\RMA\Block\Index\Guest $block */
?>

<?php if (!$block->getCustomerIsLoggedInOrNot()): ?>
    <li>
        <a href="<?= /* @noEscape */ $block->getUrl('rma/index/guest')?>">
            <?= /* @noEscape */ __('RMA')?>
        </a>
    </li>
<?php endif; ?>