<?php $_filters = $block->getActiveFilters() ?>
<?php if (empty($_filters)) {
        return;
} ?>
<div class="filter-current"  data-mage-init='{"collapsible":{"openedState": 
"active", "collapsible": true, "active": true }}'>
    <strong class="block-subtitle filter-current-subtitle widget-title"
        role="heading"
        aria-level="2"
        data-role="title"
        data-count="<?= count($_filters); ?>">
        <?= /* @noEscape */ __('Now Shopping by') ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label" attribute-code="<?= /* @noEscape */
                $_filter->getFilter()->getRequestVar() ?>" ><?= $block->escapeHtml(__($_filter->getName())); ?></span>
                <span class="filter-value" option-id='<?= /* @noEscape */
                 is_array($_filter->getValue()) ? json_encode($_filter->getValue()) :$_filter->getValue() ?>'>
                    <?= /* @noEscape */ $block->stripTags($_filter->getLabel()) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " .
                $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?= /* @noEscape */ $_filter->getRemoveUrl() ?>"
                       title="<?= /* @noEscape */ __('Previous') ?>">
                        <span><?= /* @noEscape */ __('Previous') ?></span>
                    </a>
                    <a class="action remove"
                       title="<?= /* @noEscape */ $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?= /* @noEscape */ $clearLinkUrl ?>">
                        <span><?= /* @noEscape */ $block->escapeHtml($_filter->getFilter()
                        ->getClearLinkText()) ?></span>
                    </a>
                <?php else: ?>
                    <?php
                        $removeUrl = $_filter->getRemoveUrl();
                    if ($_filter->getFilter()->getRequestVar()=='price') {
                            $url = html_entity_decode($removeUrl);
                            $removeParam = strtok($url, '?');
                            $parseUrl = parse_url($url);
                        if (isset($parseUrl['query'])) {
                                $query = $parseUrl['query'];
                                parse_str($query, $array);
                                unset($array['price']);
                                $queryNotPrice = http_build_query($array);
                                $removeUrl = $queryNotPrice ? $removeParam . '?' . $queryNotPrice : $removeParam;
                        }
                    }
                    ?>                        
                    <a class="action remove" href="<?= /* @noEscape */ $removeUrl ?>"
                       title="<?= /* @noEscape */ $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                        <span><i class="fa fa-times" aria-hidden="true"></i></span>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>