<?php if ($block->canShowBlock()): ?>
    <?php
    $viewModel = $block->getViewmodel();
    $filters = $block->getFilters();
    $layerConfig = $viewModel->getLayerConfiguration($filters);
    $filtered = count($block->getLayer()->getState()->getFilters());
    ?>
        <div class="block filter" id="layerednav-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true,
          "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        
        <div class="block-title filter-title" data-count="<?= /** @noEscape */ $filtered ?>">
            <strong data-role="title"><?= /** @noEscape */ __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content sidebar-shop sidebar-left">
                  <?php if ($block->getLayer()->getState()->getFilters()): ?>
                           <?= /** @noEscape */ $block->getChildHtml('state') ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /** @noEscape */ $block->getClearUrl() ?>" class="action clear filter-clear">
                        <span><?= /** @noEscape */ __('Clear All') ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($filters as $key => $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                            <?= /** @noEscape */ __('Shopping Options') ?>
                        </strong>
                        <div class="gradient-accordion">
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init="{&quot;accordion&quot;:{&quot;openedState&quot;: &quot;active&quot;, &quot;collapsible&quot;: true, &quot;active&quot;: false, &quot;multipleCollapsible&quot;: false}}" data-role="content">
                        <?php $wrapOptions = true;
                    endif; ?>
                    <div data-role="collapsible">
                    <div data-role="ln_collapsible" class="filter-options-item"
                         attribute="<?= /** @noEscape */ $filter->getRequestVar() ?>">
                        <div data-role="trigger" class="filter-options-title">
                        <?= /** @noEscape */ __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content">
                        <?= /** @noEscape */ $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?>
                        </div>
                    </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
                </div>
            <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>
            <?php if ($viewModel->getScopeconfig('layered_navigation/general/ajax_enable')): ?>
            <script type="text/x-magento-init">
                {
                     ".block-content.filter-content":{
                         "fAjaxLayerNav": <?= /** @noEscape */ $layerConfig ?>
                     }
                }
            </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif ?>
   

