<?php
/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_Trackorder
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

/** @var \Magento\Tax\Block\Sales\Order\Tax $block */
?>
<?php $viewModel = getData('viewModel'); ?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $viewModel->getCalculatedTaxes($_source);
    $taxIter = 0;
    $taxIter++;
?>
<?php if ($_fullInfo && $block->displayFullSummary()): ?>
    <?php foreach ($_fullInfo as $info): ?>
        <?php
            $percent    = $info['percent'];
            $amount     = $info['tax_amount'];
            $baseAmount = $info['base_tax_amount'];
            $title      = $info['title'];
        ?>
        <tr class="totals tax details details-<?= /* @noEscape */ $taxIter; ?>
            <?= /* @noEscape */ ($block->getIsPlaneMode()) ? ' plane' : '' ?>">
            <td <?= /* @noEscape */ $block->getLabelProperties(); ?>>
                <?= $block->escapeHtml($title); ?>
                <?php if ($percent !== null): ?>
                    (<?= /* @noEscape */ (float)$percent; ?>%)
                <?php endif; ?>
                <br />
            </td>
            <td <?= /* @noEscape */ $block->getValueProperties(); ?> rowspan="1">
                <?= /* @noEscape */ $_order->formatPrice($amount); ?>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif;?>

<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()): ?>
    <tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()): ?>
    <tr class="totals-tax-summary plane">
<?php else: ?>
    <tr class="totals-tax">
<?php endif; ?>
    <th <?= /* @noEscape */ $block->getLabelProperties(); ?> scope="row">
        <?php if ($block->displayFullSummary()): ?>
            <div class="detailed"><?= $block->escapeHtml(__('Tax')); ?></div>
        <?php else: ?>
            <?= $block->escapeHtml(__('Tax')); ?>
        <?php endif;?>
    </th>
    <td 
        <?= /* @noEscape */ $block->getValueProperties(); ?>
        data-th="<?= $block->escapeHtml(__('Tax')); ?>">
        <?= /* @noEscape */ $_order->formatPrice($_source->getTaxAmount()); ?>
    </td>
</tr>
