<?php

/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_RMA
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

/** @var \Ict\RMA\Block\Adminhtml\Edit\Message $block */

$messageCollection = $block->getMessageCollection();
$rmaCollection = $block->getRmaCollection();
?>

<div id="messagediv" class="message-div">
    <?php foreach ($messageCollection as $message): ?>
        <?php if ($message->getType() == "customer"): ?>
            <div class="message-lefts">
                <div class="customer_names">
                    <span class="customer_name"><?= /* @noEscape */ __($rmaCollection->getCustomerEmail()) ?></span>
                </div>
                <div class="messages">
                    <span class="msg"><?= /* @noEscape */ __($message->getMessage()) ?></span>
                    <span class="created_at"><?= /* @noEscape */ __($message->getCreatedAt()) ?></span>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($message->getType() == "admin"): ?>
            <div class="message-rights">
                <div class="customer_names">
                    <span class="customer_name"><?= /* @noEscape */ __("ADMIN") ?></span>
                </div>
                <div class="messages">
                    <span class="msg"><?= /* @noEscape */ __($message->getMessage()) ?></span>
                    <span class="created_at"><?= /* @noEscape */ __($message->getCreatedAt()) ?></span>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
