<script>
require(['jquery'], function(){

//<![CDATA[
    function import<?= /** @noEscape */ $block->getImportType();
    ?>() {

        var resultMessage = $('import_result<?= /** @noEscape */ $block->getImportType(); ?>');
        params = {
            import_type: '<?= /** @noEscape */ $block->getImportType(); ?>'
        };

        new Ajax.Request('<?= /** @noEscape */ $block->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                var validationMessage = document.getElementById
                ("import_result<?= /** @noEscape */ $block->getImportType(); ?>");
                var result = '<?= /** @noEscape */ __('Error during Import CMS Datas.') ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        validationMessage.removeClassName('hidden')
                        .addClassName('success').addClassName('message-success')
                    } else {
                        validationMessage.removeClassName('hidden').addClassName('error').addClassName('message-error')
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('error').addClassName('message-error')
                }
                validationMessage.update(result);
                setTimeout(function(){
                    location.reload();
                },3000);
            }
        });
    }

    window.import<?= /** @noEscape */ $block->getImportType(); ?>
     = import<?= /** @noEscape */ $block->getImportType(); ?>;
//]]>

});
</script>
<div class="actions actions-import-data">
    <button onclick="<?php if ($block->getButtonClass() != 'disabled'): ?>
    javascript:import<?= /** @noEscape */ $block->getImportType(); ?>();
    <?php endif; ?> return false;" class="action-import-data <?= /** @noEscape */ $block->getButtonClass(); ?>"
     type="button" id="<?= /** @noEscape */ $block->getHtmlId() ?>">
        <span><?= /** @noEscape */ $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="import_result<?= /** @noEscape */ $block->getImportType(); ?>"
     class="message-validation hidden message"></div>
</div>
