<?php
/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_Trackorder
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

/** @var \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer $block */

$_item = $block->getItem();
?>
<span class="price-excluding-tax" data-label="<?= $block->escapeHtml(__('Excl. Tax')); ?>">
    <span class="cart-price">
        <?= /* @noEscape */ $block->getOrder()->formatPrice($block->getItem()->getRowTotal()); ?>
    </span>
</span>
