<?php
/**
 * @var $block \Magento\Catalog\Block\Product\Image
 */
?>
<?php
$helper = $this->helper(Forever\Lazyload\Helper\Filter::class);
$customAttributes = !is_array($block->getCustomAttributes()) ? $block->getCustomAttributes() : null;
?>
<img class="photo image <?= /* @noEscape */ $helper->getLazyClasses() ?>"
    <?= /* @noEscape */ $customAttributes ?>
    src="<?= /* @noEscape */ $helper->getPlaceHolderUrl() ?>"
    data-src="<?= /* @noEscape */ $block->getImageUrl() ?>"
    width="<?= /* @noEscape */ $block->getWidth() ?>"
    height="<?= /* @noEscape */ $block->getHeight() ?>"
    alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" />
