<?php
/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_Trackorder
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */

/** @var \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer $block */

$_item = $block->getItem();
?>
<tr id="order-item-row-<?= /* @noEscape */ $_item->getId(); ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()); ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']); ?></dt>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <?= /* @noEscape */ $_formatedOptionValue['full_view']; ?>
                        <?php else: ?>
                            <?= /* @noEscape */ $_formatedOptionValue['value']; ?>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dd>
                        <?= /* @noEscape */ nl2br(
                            $block->escapeHtml(
                                (isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])
                            )
                        ); ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= /* @noEscape */ $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()); ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')); ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()); ?>
    </td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')); ?>">
        <?= /* @noEscape */ $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Ordered')); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyOrdered()*1; ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Shipped')); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyShipped()*1; ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?=$block->escapeHtml(__('Canceled')); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyCanceled()*1; ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Refunded')); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyRefunded()*1; ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')); ?>">
        <?= /* @noEscape */ $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
