<?php
use Forever\Team\Block\Home\Team;

$postsRecent = $block->getItems();
$isEnableModule = $block->getConfigValue();
?>
<?php if ($isEnableModule == 1): ?>
    <div class="meet-our-team-wraper">
        <div class="meet-our-team-text-block">
            <p><?= /* @noEscape */ __('Our Creative Force') ?></p>
            <h3><?= /* @noEscape */ __('Meet our team') ?></h3>
        </div>
        <div class="meet-our-team-detail-block">
            <div class="meet-our-team-margin">
        <?php foreach ($postsRecent as $post): ?>            
                <div class="meet-our-team-equal-box">
                    <div class="meet-our-team-image">
                        <img src="<?= /* @noEscape */ $block->getMediaUrl() .'team/image/'.$post->getImage()?>"
                        alt="Image" width="800" height="1078">
                    </div>
                    <div class="meet-our-team-name-designation">
                        <h2><?= /* @noEscape */ $post->getName()?></h2>
                        <h4><?= /* @noEscape */ $post->getDesignation()?></h4>
                    </div>
                </div>
        <?php endforeach;?>
            </div>
        </div>
    </div>
    <div class="view-all">
        <a class="view-all-btn action primary" href="/team">View All</a>
    </div>
<?php endif;?>
