<?php
/**
 * $block Forever\Dailydeals\Block\Dailydeals
 */
?>
<?php if ($block->isEnable()): ?>
    <?php
        date_default_timezone_set('Asia/Kolkata');
        $product = $block->getSpecificProduct();
        $image_url = $block->getProductImage($product);
        $addToCartUrl= $block->getAddCartUrl($product);
        $saleExpDateTime = explode(" ", $block->getConfigExpDateTime());
        $timeFormat = date('h:i A', strtotime($block->getConfigExpDateTime()));
        $saleExpDate = $saleExpDateTime[0];
        $currentCurrencySymbol = $block->getPriceSymbol();
        $groupPrice = $product->getPrice();
        $specialPrice = $product->getSpecialPrice();
        $formattedPrice = number_format($groupPrice, 2);
        $formattedSpecialPrice = number_format($specialPrice, 2);
        $isInStock = $product->getExtensionAttributes()->getStockItem()->getIsInStock();
    ?>
    <?php if ($isInStock): ?>
        <script type="text/javascript">
            var saleExpDate = '<?= /* @noEscape */ $saleExpDate ?>';
            var saleExpTime = '<?= /* @noEscape */ $timeFormat ?>';
            CountDownTimer((saleExpDate + ' ' + saleExpTime), 'countdown');
            function CountDownTimer(dt, id)
            {
                var end = new Date(dt);
                var _second = 1000;
                var _minute = _second * 60;
                var _hour = _minute * 60;
                var _day = _hour * 24;
                var timer;
                
                function showRemaining()
                {
                    var now = new Date();
                    var distance = end - now;
                    if (distance < 0) {
                        clearInterval(timer);
                        document.getElementById(id).innerHTML = 'Sale Over';
                        document.getElementById(id).className += 'expires';
                        document.getElementById('order-button').disabled = true;
                        document.getElementById('product-sale').style.display = 'none';
                        return;
                    }

                    var days = Math.floor(distance / _day);
                    var hours = Math.floor((distance % _day) / _hour);
                    var minutes = Math.floor((distance % _hour) / _minute);
                    var seconds = Math.floor((distance % _minute) / _second);
                    
                    if (String(hours).length < 2) {
                        hours = 0 + String(hours);
                    }
                    if (String(minutes).length < 2) {
                        minutes = 0 + String(minutes);
                    }
                    if (String(seconds).length < 2) {
                        seconds = 0 + String(seconds);
                    }
                    
                    var datestr = '<div class="counter">';
                    datestr += '<div class="counter-timer">'
                    datestr += '<p class="days-num number">' + days + '<p class="days text">';
                    datestr += '<?= /* @noEscape */ __('days') ?>' + '</p></p></div>';
                    datestr += '<div class="counter-timer">'
                    datestr += '<p class="minutes-num number">' + hours + '<p class="hours text">';
                    datestr += '<?= /* @noEscape */ __('Hrs') ?>' + '</p></p></div>';
                    datestr += '<div class="counter-timer">'
                    datestr += '<p class="minutes-num number">' + minutes + '<p class="minutes text">';
                    datestr += '<?= /* @noEscape */ __('Mins') ?>' + '</p></p></div>';
                    datestr += '<div class="counter-timer">'
                    datestr += '<p class="seconds-num number">' + seconds + '<p class="seconds text">';
                    datestr += '<?= /* @noEscape */ __('Secs') ?>' + '</p></p></div></div>';
                    document.getElementById(id).innerHTML = datestr;
                }
                timer = setInterval(showRemaining, 1000);
            }
        </script>

        <div id="product-sale" class="daily-deals-section">
            <div class="daily-deals-inner d-flex flex-wrap align-items-center justify-content-between">
                <div id="sale-description" class="daily-deals-title bestseller-slider-section">
                    <div class="page-title-wrapper">
                        <h3 class="sale-description-text page-title">
                            <span><?= /* @noEscape */ __($block->getConfigSaleText()) ?></span>
                        </h3>
                    </div>
                </div>
                <div class="daily-deals-left">
                    <div id="sale-header">
                        <div id="product-image">
                            <img width="200" height="170" src="<?= /* @noEscape */ $image_url; ?>">
                        </div>
                    </div>
                </div>
                <div class="daily-deals-right">
                    <div class="sale-body">
                        <div class="product-name">
                            <span class="name">
                                <?= /* @noEscape */ __($product->getName()) ?>
                            </span>
                        </div>
                        <div class="product-price">
                            <?php if ($product->getSpecialPrice()): ?>
                                <span class="regular-price">
                                    <?= /* @noEscape */ __($currentCurrencySymbol . $formattedPrice) ?>
                                </span>
                                <span class="special-price">
                                    <?= /* @noEscape */ __($currentCurrencySymbol . $formattedSpecialPrice) ?>
                                </span>
                            <?php else: ?>
                                <span class="price">
                                    <?= /* @noEscape */ __($currentCurrencySymbol . $formattedPrice) ?>
                                </span>
                            <?php endif; ?>
                        </div>
                        <div class="sale-footer">
                            <div class="addtocart-button">
                                <form data-role="tocart-form" action="<?= /* @noEscape */ $addToCartUrl; ?>" method="post"> 
                                    <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                        title="<?= /* @noEscape */ __($block->getConfigButtonText()) ?>"
                                        id="order-button"
                                        class="action tocart primary">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        <span><?= /* @noEscape */ __($block->getConfigButtonText()) ?></span>
                                     </button>
                                 </form>
                            </div>
                        </div>
                    </div>
                    <div id="countdown"></div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<script>
require(['jquery','jquery/ui'], function ($) {
    $(document).ready(function(){
        $(function() {
            var elementPosition = $('.daily-deals-section').offset();

            $(window).scroll(function(){
                    if($(window).scrollTop() > elementPosition.top){
                         $('.daily-deals-section').addClass('stick');
                    } else {
                        $('.daily-deals-section').removeClass('stick');
                    }    
            });
        })
    });
});
</script>
