<?php
/**
 * Copyright © Icreative Technologies. All rights reserved.
 *
 * @author : Icreative Technologies
 * @package : Ict_Cancelorder
 * @copyright : Copyright © Icreative Technologies (https://www.icreativetechnologies.com/)
 */
?>
<?php $viewModel = $block->getData('viewModel'); ?>
<?php $enableIctCancelOrder = $viewModel->getConfig("cancelorder/general/enable"); ?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info'); ?>
<?php if ($_orders && !empty($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @noEscape */ $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= /* @noEscape */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ;?>
                    <th scope="col" class="col shipping"><?= /* @noEscape */ $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= /* @noEscape */ $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= /* @noEscape */ $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?= /* @noEscape */ $_order->getRealOrderId() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                        </td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                            <?php if ($_order->getShippingAddress()): ?>
                                <?= $block->escapeHtml($_order->getShippingAddress()->getName()); ?>
                            <?php else: ?>
                                <?= '&nbsp;'; ?>
                            <?php endif; ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Order Total')) ?>" class="col total">
                            <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?= /* @noEscape */ $_order->getStatusLabel() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @noEscape */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($viewModel->getReorder($_order->getEntityId())): ?>
                                <a
                                    href="#"
                                    data-post=
                                        '<?= /* @noEscape */
                                            $viewModel->getPostData($block->getReorderUrl($_order)) ?>'
                                            class="action order">
                                            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($_order->canCancel() && $enableIctCancelOrder == 1): ?>
                                <a 
                                    href="javascript:void(0)"
                                    class="cancel-btn"
                                    data-id="<?= /* @noEscape */ $_order->getEntityId() ?>"
                                    data-action="<?= /* @noEscape */
                                        $block->getUrl('cancelorder/index/orderdetails') ?>">
                                    <?= $block->escapeHtml(__('Cancel Order')) ?>
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= /* @noEscape */ $block->getPagerHtml(); ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
    </div>
<?php endif; ?>

<div class="cancelorder-popup"></div>

<script type="text/x-magento-init">
    {
        "#cancel-form": {
            "validation": {}
        }
    }
</script>
