<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
 <?php
    $viewModel = $block->getViewmodels();
    $enable = $viewModel->getScopeconfig();
    if ($enable == 1) { ?>
        <?php if ($block->getWishlistHelper()->isAllow()): ?>
   <a href="#"
       onclick="addProductToWishlist(this)"
       class="action towishlist"
       product-id='<?= /* @noEscape */ $productId =
        json_decode($block->getAddToWishlistParams($block->getProduct()), true)['data']['product'] ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
<?php endif; ?>
<script>
window.addProductToWishlist = function (obj) {
    if(!parseInt(obj)){
        var id = obj.getAttribute('product-id');
    }else{
        var id = obj;
    }
    
    require(["jquery"], function($){
        $.ajax({
            url: '<?= /* @noEscape */ $block->getUrl('ajaxlogin/index/addtowishlist') ?>',
            method: 'get',
            data: { productId: id},
            dataType: 'json',
            showLoader:true,
            success: function(data){
                if(data.status=="400"){
                    localStorage.removeItem('wishlist_elem');    
                    localStorage.setItem('wishlist_elem', id);
                    $('.trigger-ajax-login').eq(0).trigger('click');
                }else{
                    var redirect = data.redirect;
                    localStorage.removeItem('wishlist_elem');
                    if(redirect) {
                        window.location.href = '<?= /* @noEscape */ $block->getUrl('wishlist/index/index') ?>';
                    } else {
                      <?= /* @noEscape */ "success"; ?> 
                    }
                }
            }
        });


    });
}
</script>
  <?php  } else {

        if ($block->getWishlistHelper()->isAllow()): ?>
    <a href="#"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif;

  } ?>